---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: true

dotfiles_repo: https://github.com/craigpearson/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/code/private/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - wget
  - git
  - composer
  - nvm
  - ssh-copy-id
  - openssl
  - yarn
  - mackup

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - google-chrome
  - firefox
  - postman
  - adobe-creative-cloud
  - lastpass
  - microsoft-office
  - microsoft-teams
  - slack
  - rectangle
  - vagrant
  - virtualbox
  - spotify
  - the-unarchiver
  - dash
  - omnidisksweeper
  - cyberduck
  - forticlient-vpn
  - vlc
  - powershell
  - alfred
  - tower
  - transmit
  - whatsapp
  - nordvpn


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Music
  - News
  - 'App Store'
dockitems_persist:
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2
  - name: "Postman"
    path: "/Applications/Postman.app/"
    pos: 3
  - name: "Tower"
    path: "/Applications/Tower.app/"
    pos: 4
  - name: "Safari"
    path: "/Applications/Google Chrome.app/"
    pos: 5
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
    pos: 6
  - name: "Notes"
    path: "/Applications/Notes.app/"
    pos: 7
  - name: "Reminders"
    path: "/Applications/Reminders.app/"
    pos: 8
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 9
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 10
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 11


osx_script: "~/code/private/dotfiles/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
